events { worker_connections 1024; }

http {
    upstream backend_servers {
        server app1:5678;
        server app2:5678;
        server app3:5678;
    }

    server {
        listen 80;

        # Favicon verzoeken negeren om de loadbalancing beter zichtbaar te maken
        location = /favicon.ico {
            return 204;
            access_log off;
        }

        location / {
            proxy_pass http://backend_servers;

            # HTTP Headers: Forcefully disable Client-Side Caching
            add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
            expires off;
        }
    }
}